export default [
  { key: 'VE', text: 'Venezuela' },
  { key: 'AR', text: 'Argentina' },
  { key: 'RU', text: 'Russia' },
  { key: 'TH', text: 'Thailand' },
  { key: 'ID', text: 'Indonesia' },
  { key: 'CN', text: 'China' },
  { key: 'PH', text: 'Philippines' },
  { key: 'PE', text: 'Peru' },
  { key: 'HR', text: 'Croatia' },
  { key: 'GR', text: 'Greece' },
  { key: 'CZ', text: 'Czech Republic' },
  { key: 'PT', text: 'Portugal' },
  { key: 'US', text: 'United States' },
  { key: 'AM', text: 'Armenia' },
  { key: 'CA', text: 'Canada' },
  { key: 'BR', text: 'Brazil' },
  { key: 'FR', text: 'France' },
  { key: 'PL', text: 'Poland' },
]
